import { PROMPT_DEX_SCHEMA_VERSION, type PromptEntry } from './types'

/**
 * 初期収録プロンプト(builtin)。
 *
 * SunoとUdioで「効き方」が違うため、主要ジャンルはサービス別に作り分けている。
 * - Suno: スタイル欄は4〜7語のカンマ区切り(ジャンル→テンポ→楽器→ボーカル→質感→雰囲気)。
 *   BPMは目安程度。不要な音は Style ではなく Exclude Styles 欄へ。構成は歌詞欄の [Verse]/[Chorus] タグ。
 * - Udio: 情景を文章で描写する自然言語型(セッションミュージシャンに指示する感覚)。
 *   Prompt Strength で忠実度を調整、強調したい語は繰り返す、精密制御は Manual Mode。
 *
 * 実在する存命アーティストの模倣は入れない(色・雰囲気・構成で表現)。
 * createdAt は収録順を安定させるための固定値。
 */

const D = '2026-07-22T00:00:00.000Z'

function b(
  id: string,
  e: Omit<PromptEntry, 'id' | 'createdAt' | 'updatedAt' | 'source' | 'schemaVersion'>,
): PromptEntry {
  return {
    id,
    ...e,
    createdAt: D,
    updatedAt: D,
    source: 'builtin',
    schemaVersion: PROMPT_DEX_SCHEMA_VERSION,
  }
}

// Suno/Udio共通で使い回す「サービス別のコツ」
const SUNO_TIP_STRUCTURE = '構成は歌詞欄の [Verse]/[Chorus] などのタグで指定できる'
const SUNO_TIP_EXCLUDE = '不要な音は Style欄に「no 〜」と書かず、Exclude Styles 欄へ入れる'
const SUNO_FAIL_CROWD = '語を詰め込みすぎ(8語以上)ると指定同士が競合してぼやける'
const SUNO_FAIL_BPM = 'BPMは厳密には効かず、あくまで目安として扱われる'
const UDIO_TIP_STRENGTH = 'Prompt Strength を上げると忠実度が上がり、下げると多様性が出る'
const UDIO_TIP_REPEAT = '強調したい要素は語を2回書くと効きやすい'
const UDIO_TIP_MANUAL = '細部まで固定したいときは Manual Mode(タグのみ)で作り込む'
const UDIO_FAIL_CONFLICT = '矛盾するタグ(明るい×暗い等)を混ぜると破綻しやすい'

export const BUILTIN_PROMPTS: PromptEntry[] = [
  // ===== J-POP =====
  b('bp-jpop-bright', {
    title: '【Suno】疾走感のある明るいJ-POP',
    prompt: 'bright J-pop, upbeat 128 BPM, clean electric guitar and punchy drums, clear female vocal, polished production, catchy and uplifting',
    description: '前向きで疾走感のある王道J-POP。Suno向けに要素を6語へ絞り、サビで開ける明るさを狙います。',
    genre: 'J-POP',
    subgenre: 'ポップロック',
    emotions: ['前向き', '爽やか', 'エモい'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['エレキギター', 'ドラム', 'シンセ'],
    era: '2020s',
    uses: ['MV', 'YouTube', 'タイアップ'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: [
      '「catchy / uplifting」でサビが明るくまとまりやすい',
      'ジャンル→テンポ→楽器→ボーカルの順で並べると各指定が効く',
    ],
    failurePoints: [SUNO_FAIL_CROWD, SUNO_FAIL_BPM],
    adjustments: [
      SUNO_TIP_STRUCTURE + '(サビは [Chorus] を明示)',
      '声を柔らかくしたいときは clear female vocal を warm female vocal に変える',
    ],
    tags: ['王道', 'サビ映え', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-jpop-bright-udio', {
    title: '【Udio】疾走感のある明るいJ-POP',
    prompt:
      'An upbeat, uplifting modern J-pop song with driving energy — bright clean electric guitars, punchy live drums, sparkling synths, and a clear emotive female lead vocal. Polished radio-ready production, big catchy chorus, hopeful and energetic mood.',
    description: 'Udio向けに情景を文章で描写した明るいJ-POP。Prompt Strengthを高めにすると狙いへ寄ります。',
    genre: 'J-POP',
    subgenre: 'ポップロック',
    emotions: ['前向き', '爽やか', 'エモい'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['エレキギター', 'ドラム', 'シンセ'],
    era: '2020s',
    uses: ['MV', 'YouTube', 'タイアップ'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: [
      '「big catchy chorus」を文章に入れるとサビの押しが出る',
      UDIO_TIP_STRENGTH,
    ],
    failurePoints: [UDIO_FAIL_CONFLICT, 'Prompt Strength が低いと prompt から離れて平凡になる'],
    adjustments: [
      UDIO_TIP_REPEAT + '(例: catchy を2回)',
      '明るさを足すなら bright / sparkling を、落ち着けるなら mellow を加える',
    ],
    tags: ['王道', 'サビ映え', 'Udio向け'],
    version: 'v1',
  }),

  // ===== バラード =====
  b('bp-jpop-ballad', {
    title: '【Suno】泣けるピアノバラード',
    prompt: 'emotional pop ballad, slow 68 BPM, grand piano and warm strings, soft female vocal, spacious reverb, heartfelt and nostalgic',
    description: '静かに始まり後半で盛り上げる泣かせ系バラード。Suno向けに6語構成。歌詞を届けたいときに。',
    genre: 'バラード',
    subgenre: 'ピアノバラード',
    emotions: ['切ない', '感動的', 'ノスタルジック'],
    bpm: 'slow',
    vocal: 'female',
    instruments: ['ピアノ', 'ストリングス'],
    era: '2010s',
    uses: ['MV', '結婚式', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: [
      'ピアノ+ストリングスは安定して「泣ける」質感になりやすい',
      'slow 68 BPM で歌詞が聴き取りやすくなる',
    ],
    failurePoints: ['reverbが強いと言葉がぼやける', SUNO_FAIL_BPM],
    adjustments: [
      'ラスサビを厚くするなら [Chorus: soaring vocals, swelling strings] と : で指定',
      SUNO_TIP_EXCLUDE + '(打ち込み感を消すなら drums を除外)',
    ],
    tags: ['バラード', '泣ける', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-ballad-udio', {
    title: '【Udio】壮大なピアノバラード',
    prompt:
      'A heartfelt, cinematic piano ballad that starts intimate and swells to a powerful climax — gentle grand piano, warm swelling strings, subtle pads, and a soft emotive female vocal. Nostalgic and moving, with spacious natural reverb and dynamic build.',
    description: 'Udio向けに「静→大」の展開を文章で描いたバラード。忠実度が高く、盛り上がりを作りやすい構成です。',
    genre: 'バラード',
    subgenre: 'ピアノバラード',
    emotions: ['切ない', '感動的', 'ノスタルジック'],
    bpm: 'slow',
    vocal: 'female',
    instruments: ['ピアノ', 'ストリングス'],
    era: '2010s',
    uses: ['MV', '結婚式', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: [
      '「starts intimate and swells to a climax」で山を作れる',
      'Udioは音質が滑らかで、生ピアノ+ストリングスが映える',
    ],
    failurePoints: ['盛り込みすぎると静けさが失われる', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_STRENGTH, '言葉を立てたいときは intimate / vulnerable を強調する'],
    tags: ['バラード', '泣ける', 'Udio向け'],
    version: 'v1',
  }),

  // ===== ロック =====
  b('bp-rock-band', {
    title: '【Suno】骨太なバンドロック',
    prompt: 'driving alternative rock, fast 150 BPM, distorted guitars and powerful drums, prominent bass, raw male vocal, live band energy',
    description: 'ライブ感のある骨太ロック。Suno向けに編成を名指しして生バンド感を安定させます。',
    genre: 'ロック',
    subgenre: 'オルタナ',
    emotions: ['熱い', '力強い', '疾走感'],
    bpm: 'fast',
    vocal: 'male',
    instruments: ['エレキギター', 'ベース', 'ドラム'],
    era: '2010s',
    uses: ['MV', 'ライブ', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: [
      '「live band energy」で打ち込み臭さが減る',
      'guitars/bass/drums を名指しするとバンド編成が安定',
    ],
    failurePoints: ['distortionを強調しすぎると歌が埋もれる', SUNO_FAIL_CROWD],
    adjustments: [
      'サビを厚くするなら [Chorus: double-tracked guitars] と指定',
      '歌を前に出したいときは production を balanced に寄せる',
    ],
    tags: ['バンド', 'ギター', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-rock-udio', {
    title: '【Udio】ライブ感のあるロック',
    prompt:
      'A raw, high-energy alternative rock song that feels like a live band in a room — crunchy distorted electric guitars, a driving rhythm section with punchy drums and a thick bass line, and a gritty passionate male vocal. Loud, dynamic, and anthemic.',
    description: 'Udio向けに「ライブの一室」の空気感を描写したロック。生々しい質感が得意なUdioと相性◎。',
    genre: 'ロック',
    subgenre: 'オルタナ',
    emotions: ['熱い', '力強い', '疾走感'],
    bpm: 'fast',
    vocal: 'male',
    instruments: ['エレキギター', 'ベース', 'ドラム'],
    era: '2010s',
    uses: ['MV', 'ライブ', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: [
      '「live band in a room」で生っぽい空気が出る',
      'Udioは歪みやアタックの質感が自然に出やすい',
    ],
    failurePoints: ['gritty を盛りすぎるとボーカルが荒れる', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_REPEAT + '(driving を繰り返すと疾走感が増す)', UDIO_TIP_MANUAL],
    tags: ['バンド', 'ギター', 'Udio向け'],
    version: 'v1',
  }),

  // ===== アニソン =====
  b('bp-anison-op', {
    title: '【Suno】アニメOP風の高揚アニソン',
    prompt: 'anime opening, high energy 175 BPM, fast drums and bright synth leads, orchestral hits, powerful female vocal, soaring epic chorus',
    description: '90秒で映えるアニメOP的な高揚感。Suno向けに要素を絞り、前奏→サビの爆発を狙います。',
    genre: 'アニソン',
    subgenre: 'OP/主題歌',
    emotions: ['高揚', '前向き', 'エモい'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['シンセ', 'ドラム', 'オーケストラヒット'],
    era: '2020s',
    uses: ['MV', 'Shorts', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「soaring epic chorus」でOPらしい爆発力が出る', 'orchestral hits が疾走感に厚みを足す'],
    failurePoints: [SUNO_FAIL_CROWD, 'テンポが速く歌詞が詰め込み気味になりがち'],
    adjustments: [
      'サビ手前に [Pre-Chorus] を置いて溜めを作る',
      SUNO_TIP_STRUCTURE,
    ],
    tags: ['アニソン', '高揚', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-anison-udio', {
    title: '【Udio】疾走するアニソンOP',
    prompt:
      'A fast, energetic anime opening theme with a soaring, epic chorus — driving double-kick drums, bright synth leads, dramatic orchestral hits, and a powerful female lead vocal. Cinematic, uplifting, and triumphant, building to a huge hook.',
    description: 'Udio向けに構築感を文章で描いたアニソンOP。オーケストラ×バンドの厚みを出したいときに。',
    genre: 'アニソン',
    subgenre: 'OP/主題歌',
    emotions: ['高揚', '前向き', 'エモい'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['シンセ', 'ドラム', 'オーケストラヒット'],
    era: '2020s',
    uses: ['MV', 'Shorts', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「building to a huge hook」でサビへの流れが作れる', 'Udioは厚いレイヤーを破綻なくまとめやすい'],
    failurePoints: ['要素が多く音が団子になりやすい', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_STRENGTH, 'サビだけ強めたいなら epic / soaring を繰り返す'],
    tags: ['アニソン', '高揚', 'Udio向け'],
    version: 'v1',
  }),

  // ===== Lo-fi =====
  b('bp-lofi-study', {
    title: '【Suno】作業がはかどるLo-fiビート',
    prompt: 'lo-fi hip hop, chill 82 BPM, mellow piano and dusty drums, warm bass, instrumental, vinyl crackle, relaxed and nostalgic',
    description: '勉強・作業向けの主張しないLo-fi。Suno向けに歌なし指定を明確化。長時間流しても疲れません。',
    genre: 'Lo-fi',
    subgenre: 'チルホップ',
    emotions: ['落ち着く', 'ノスタルジック', '穏やか'],
    bpm: 'mid',
    vocal: 'instrumental',
    instruments: ['ピアノ', 'ドラム', 'ベース'],
    era: '2020s',
    uses: ['作業用BGM', 'YouTube', '配信'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['vinyl crackle でLo-fiらしさが一気に出る', '「instrumental」明記で作業の邪魔をしない'],
    failurePoints: ['メロが強すぎると作業用から外れる', SUNO_FAIL_BPM],
    adjustments: [
      '歌なしを確実にするなら Instrumental を ON にし、Exclude に vocals を入れる',
      '眠くしたくないときは 82→90 BPM へ上げる',
    ],
    tags: ['作業用', 'チル', 'インスト', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-lofi-udio', {
    title: '【Udio】夜のLo-fiインスト',
    prompt:
      'A warm, hazy lo-fi hip hop instrumental for a late night — mellow Rhodes piano, dusty boom-bap drums, soft upright bass, vinyl crackle and tape hiss. Relaxed, nostalgic, and cozy, with a laid-back groove and no vocals.',
    description: 'Udio向けに夜の空気を描写したLo-fi。テープ質感まで文章で指定でき、雰囲気が濃く出ます。',
    genre: 'Lo-fi',
    subgenre: 'チルホップ',
    emotions: ['ノスタルジック', '穏やか', '大人っぽい'],
    bpm: 'mid',
    vocal: 'instrumental',
    instruments: ['エレピ', 'ドラム', 'ベース'],
    era: '2020s',
    uses: ['作業用BGM', 'YouTube', '配信'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「tape hiss / vinyl crackle」で質感が濃く出る', 'Udioは滑らかな音で長尺BGM化しやすい'],
    failurePoints: ['展開を付けすぎると作業の邪魔になる', 'Prompt Strength が低いとメロが立ちすぎる'],
    adjustments: ['歌なしを保つため no vocals を明記し繰り返す', UDIO_TIP_STRENGTH],
    tags: ['作業用', 'チル', '夜', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-lofi-shorts', {
    title: '【Suno】Shorts映えするチルフック',
    prompt: 'chill lo-fi pop, 90 BPM, mellow keys and boom-bap drums, soft female vocal, catchy short hook, warm and loopable',
    description: '冒頭にフックを置いた短尺向けLo-fi。ShortsやTikTokでループ再生されやすい構成を狙います。',
    genre: 'Lo-fi',
    subgenre: 'チルポップ',
    emotions: ['穏やか', 'かわいい', '落ち着く'],
    bpm: 'mid',
    vocal: 'female',
    instruments: ['キーボード', 'ドラム'],
    era: '2020s',
    uses: ['Shorts', 'TikTok', 'ループ'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「catchy short hook / loopable」で冒頭離脱を減らせる', '短いフックが繰り返しに向く'],
    failurePoints: ['イントロが長いとShortsで飛ばされる', SUNO_FAIL_BPM],
    adjustments: ['歌詞の先頭に [Chorus] を置いてサビ始まりにする', '15〜30秒で完結するよう展開を絞る'],
    tags: ['Shorts', 'ループ', 'フック', 'チル', 'Suno向け'],
    version: 'v1',
  }),

  // ===== EDM =====
  b('bp-edm-festival', {
    title: '【Suno】フェス映えEDMアンセム',
    prompt: 'festival EDM anthem, big room 128 BPM, huge supersaw drop and punchy kick, sidechain pump, energetic female vocal, euphoric and wide',
    description: 'ドロップを主役にしたフェス系EDM。Suno向けにbuild→dropの語で高揚を狙います。',
    genre: 'EDM',
    subgenre: 'ビッグルーム',
    emotions: ['高揚', '爽快', 'パワフル'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['シンセ', 'キック'],
    era: '2010s',
    uses: ['MV', 'クラブ', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['sidechain pump でEDMらしいうねりが出る', '「euphoric / wide」で高揚感が乗る'],
    failurePoints: ['ドロップが濁ると爆発力が半減', 'ボーカルとシンセが同帯で干渉しやすい'],
    adjustments: ['歌詞に [Build-up] → [Drop] を置いてメリハリを付ける', SUNO_TIP_EXCLUDE],
    tags: ['EDM', 'ドロップ', '高揚', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-edm-udio', {
    title: '【Udio】高揚するEDMアンセム',
    prompt:
      'A euphoric festival EDM anthem with a massive drop — soaring supersaw synths, a punchy four-on-the-floor kick, heavy sidechain pumping, and an energetic female topline. Big build-up into an explosive, wide, hands-in-the-air chorus. Bright and powerful.',
    description: 'Udio向けにbuild→dropの流れを文章で描いたEDM。高揚のピークを言葉で作り込めます。',
    genre: 'EDM',
    subgenre: 'ビッグルーム',
    emotions: ['高揚', '爽快', 'パワフル'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['シンセ', 'キック'],
    era: '2010s',
    uses: ['MV', 'クラブ', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「big build-up into an explosive chorus」でメリハリが出る', 'Udioは太いシンセを破綻なく鳴らしやすい'],
    failurePoints: ['要素過多でドロップが渋滞する', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_REPEAT + '(euphoric を繰り返す)', '刺さりを抑えるなら bright を warm に'],
    tags: ['EDM', 'ドロップ', '高揚', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-future-bass', {
    title: '【Suno】きらめくフューチャーベース',
    prompt: 'future bass, 150 BPM half-time, lush supersaw chords, pitched vocal chops, soft female vocal, punchy drums, shimmering and emotional',
    description: 'きらびやかで感情的なフューチャーベース。Suno向けにchops＋chordsで透明感を出します。',
    genre: 'EDM',
    subgenre: 'フューチャーベース',
    emotions: ['エモい', '透明感', '高揚'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['シンセ', 'ボーカルチョップ', 'ドラム'],
    era: '2020s',
    uses: ['MV', 'YouTube', 'Shorts'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['vocal chops+lush chords で「きらめき」が出る', 'half-time で疾走と重さのバランスが取れる'],
    failurePoints: ['コードが厚すぎるとボーカルが埋もれる', '高音が刺さり聴き疲れしやすい'],
    adjustments: ['ボーカルを立てるなら lush chords を soft chords に', SUNO_TIP_EXCLUDE],
    tags: ['きらめき', 'エモい', 'ドロップ', 'Suno向け'],
    version: 'v1',
  }),

  // ===== ゲーム音楽 =====
  b('bp-game-battle', {
    title: '【Suno】ゲームのバトル曲(オーケストラ)',
    prompt: 'epic orchestral battle theme, fast 140 BPM, driving strings and powerful brass, taiko and orchestral percussion, choir swells, instrumental, cinematic and intense',
    description: '緊張感のあるボス戦向けインスト。Suno向けに和洋の打楽器を指定して迫力を出します。',
    genre: 'ゲーム音楽',
    subgenre: 'オーケストラ',
    emotions: ['緊張感', '壮大', '力強い'],
    bpm: 'fast',
    vocal: 'instrumental',
    instruments: ['ストリングス', 'ブラス', 'パーカッション'],
    era: 'timeless',
    uses: ['ゲーム', 'BGM', '配信'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「cinematic / intense」で緊張感が出る', 'taiko+choir で和洋折衷の迫力が作れる'],
    failurePoints: ['要素が多くミックスが団子になりやすい', 'ループ用途だと展開が付きすぎる'],
    adjustments: ['ループ化するなら seamless loop, minimal development を足す', SUNO_TIP_EXCLUDE + '(歌なしは vocals を除外)'],
    tags: ['ゲーム', 'オーケストラ', 'インスト', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-game-udio', {
    title: '【Udio】壮大なゲームのバトル曲',
    prompt:
      'An intense, cinematic orchestral battle theme for a video game boss fight — relentless staccato strings, heroic brass stabs, thunderous taiko and orchestral percussion, and dramatic choir swells. Dark, epic, and driving, with a sense of rising danger. Instrumental, no vocals.',
    description: 'Udio向けに緊迫感を文章で描いたバトル曲。厚いオーケストラを滑らかにまとめたいときに。',
    genre: 'ゲーム音楽',
    subgenre: 'オーケストラ',
    emotions: ['緊張感', '壮大', '力強い'],
    bpm: 'fast',
    vocal: 'instrumental',
    instruments: ['ストリングス', 'ブラス', 'パーカッション'],
    era: 'timeless',
    uses: ['ゲーム', 'BGM', '配信'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「rising danger」で緊迫の高まりが作れる', 'Udioは大編成でも音が濁りにくい'],
    failurePoints: ['盛り込みすぎて主旋律が埋もれる', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_MANUAL, 'ループ用途なら seamless, minimal development を明記して繰り返す'],
    tags: ['ゲーム', 'オーケストラ', 'インスト', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-game-chiptune', {
    title: '【Suno】レトロなチップチューン',
    prompt: 'upbeat chiptune, 8-bit, 145 BPM, square and pulse leads, arpeggios, noise percussion, instrumental, playful and nostalgic',
    description: 'レトロゲーム風の8bitインスト。Suno向けに音源名を指定してレトロ感を確実に出します。',
    genre: 'ゲーム音楽',
    subgenre: 'チップチューン',
    emotions: ['楽しい', 'ノスタルジック', 'かわいい'],
    bpm: 'fast',
    vocal: 'instrumental',
    instruments: ['シンセ(8bit)', 'アルペジオ'],
    era: 'retro',
    uses: ['ゲーム', 'BGM', 'Shorts'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「8-bit / square lead」でレトロ感が確実に出る', 'アルペジオが手軽に賑やかさを足す'],
    failurePoints: ['音色が単調で長尺だと飽きやすい', 'ベースが弱いと軽くなりすぎる'],
    adjustments: ['厚みが欲しいときは bass line, drums を足す', '少しリッチにするなら 8-bit を 16-bit chiptune に'],
    tags: ['チップチューン', 'レトロ', 'インスト', 'Suno向け'],
    version: 'v1',
  }),

  // ===== 作業用BGM =====
  b('bp-ambient-focus', {
    title: '【Suno】集中できるアンビエントピアノ',
    prompt: 'ambient piano, minimal, very slow 60 BPM, soft felt piano, airy pads, gentle textures, instrumental, calm and focused',
    description: '深い集中・睡眠導入向けの静かなインスト。Suno向けに「no drums」ではなくExcludeで抜きます。',
    genre: '作業用BGM',
    subgenre: 'アンビエント',
    emotions: ['静か', '落ち着く', '癒し'],
    bpm: 'slow',
    vocal: 'instrumental',
    instruments: ['ピアノ', 'パッド'],
    era: '2020s',
    uses: ['作業用BGM', '睡眠', '瞑想'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['felt piano の柔らかさが長時間でも疲れにくい', '「minimal / calm」で集中の邪魔をしない'],
    failurePoints: ['展開を付けすぎると集中が切れる', 'パッドが厚すぎると眠すぎ/重すぎになる'],
    adjustments: ['リズムを消すなら drums / beat を Exclude Styles へ', '眠らせたくないときは 60→72 BPM へ'],
    tags: ['作業用', '睡眠', 'ピアノ', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-ambient-udio', {
    title: '【Udio】癒しのアンビエント',
    prompt:
      'A calm, minimal ambient piece for deep focus and relaxation — soft felt piano, airy evolving pads, gentle field-recording textures, and warm reverb. Spacious, weightless, and soothing, with no drums and no vocals. Slow and meditative.',
    description: 'Udio向けに静けさを文章で描いたアンビエント。空間の広がりを言葉で作り込めます。',
    genre: '作業用BGM',
    subgenre: 'アンビエント',
    emotions: ['静か', '落ち着く', '癒し'],
    bpm: 'slow',
    vocal: 'instrumental',
    instruments: ['ピアノ', 'パッド'],
    era: '2020s',
    uses: ['作業用BGM', '睡眠', '瞑想'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「spacious / weightless」で広がりが出る', 'Udioは長い持続音を滑らかに保てる'],
    failurePoints: ['要素を足すと静けさが崩れる', 'Prompt Strength が低いとリズムが混ざることがある'],
    adjustments: ['「no drums / no vocals」を明記し繰り返す', UDIO_TIP_STRENGTH],
    tags: ['作業用', '睡眠', 'ピアノ', 'Udio向け'],
    version: 'v1',
  }),

  // ===== Shorts向け =====
  b('bp-shorts-hook', {
    title: '【Suno】Shorts向けフック先行ポップ',
    prompt: 'catchy pop, hook-first, upbeat 118 BPM, bright synth and punchy claps, bright female vocal, simple arrangement, high-energy intro',
    description: '最初の2秒で掴む短尺特化ポップ。Suno向けに構成をシンプルに保ち歌を主役にします。',
    genre: 'Shorts向け',
    subgenre: 'ポップ',
    emotions: ['楽しい', '前向き', 'キャッチー'],
    bpm: 'upper',
    vocal: 'female',
    instruments: ['シンセ', 'クラップ'],
    era: '2020s',
    uses: ['Shorts', 'TikTok', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「hook-first / high-energy intro」で冒頭離脱に強い', 'シンプル編成で歌が主役になる'],
    failurePoints: ['サビが弱いと最後まで見られない', SUNO_FAIL_CROWD],
    adjustments: ['歌詞は [Chorus] から始めてフックを最前面に', 'ループ向けに終わりを頭とつなげる'],
    tags: ['Shorts', 'フック', 'キャッチー', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-shorts-udio', {
    title: '【Udio】Shorts向けフック先行ポップ',
    prompt:
      'A catchy, high-energy pop song built around an instantly memorable hook that hits in the first two seconds — bright plucky synths, punchy claps, and a bright confident female vocal. Simple, punchy arrangement, loopable, vertical-video friendly. Fun and upbeat.',
    description: 'Udio向けに「冒頭2秒で掴む」設計を文章化したShorts用ポップ。掴みの強さを言葉で作れます。',
    genre: 'Shorts向け',
    subgenre: 'ポップ',
    emotions: ['楽しい', '前向き', 'キャッチー'],
    bpm: 'upper',
    vocal: 'female',
    instruments: ['シンセ', 'クラップ'],
    era: '2020s',
    uses: ['Shorts', 'TikTok', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「hook that hits in the first two seconds」で掴みが強い', UDIO_TIP_REPEAT + '(catchy を繰り返す)'],
    failurePoints: ['編成が寂しいと尺が持たない', 'Prompt Strength が低いとフックがぼやける'],
    adjustments: ['ループ用に loopable を明記', UDIO_TIP_STRENGTH],
    tags: ['Shorts', 'フック', 'キャッチー', 'Udio向け'],
    version: 'v1',
  }),

  // ===== インストゥルメンタル =====
  b('bp-acoustic-inst', {
    title: '【Suno】優しいアコースティックギター',
    prompt: 'warm acoustic guitar, 92 BPM, fingerpicked steel-string guitar, light percussion, soft upright bass, instrumental, gentle and heartfelt',
    description: '素朴で温かいアコースティックのインスト。Suno向けに奏法を指定して生っぽさを出します。',
    genre: 'インストゥルメンタル',
    subgenre: 'アコースティック',
    emotions: ['穏やか', '温かい', '癒し'],
    bpm: 'mid',
    vocal: 'instrumental',
    instruments: ['アコースティックギター', 'ベース', 'パーカッション'],
    era: 'timeless',
    uses: ['BGM', 'Vlog', '作業用BGM'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「fingerpicked」で生っぽい表情が出る', '編成が薄めで映像の邪魔をしない'],
    failurePoints: ['同じフレーズの繰り返しで単調になりやすい', 'パーカッションが強いと素朴さが減る'],
    adjustments: ['変化が欲しいときは中盤に piano を足す', 'より静かにするなら percussion を Exclude へ'],
    tags: ['アコギ', '癒し', 'インスト', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-acoustic-udio', {
    title: '【Udio】温かいアコースティックインスト',
    prompt:
      'A warm, intimate acoustic instrumental with an organic, in-the-room feel — gently fingerpicked steel-string guitar, soft upright bass, light hand percussion, and a touch of piano. Heartfelt, cozy, and unhurried, with natural room ambience. No vocals.',
    description: 'Udio向けに「部屋の空気」を描いたアコースティック。生録りのような温もりが得意です。',
    genre: 'インストゥルメンタル',
    subgenre: 'アコースティック',
    emotions: ['穏やか', '温かい', '癒し'],
    bpm: 'mid',
    vocal: 'instrumental',
    instruments: ['アコースティックギター', 'ベース', 'ピアノ'],
    era: 'timeless',
    uses: ['BGM', 'Vlog', '作業用BGM'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「in-the-room feel / room ambience」で生録り感が出る', 'Udioは生楽器の質感を自然に再現しやすい'],
    failurePoints: ['要素を足すと素朴さが薄れる', 'Prompt Strength が低いと歌が入ることがある'],
    adjustments: ['歌なしを保つため no vocals を明記', UDIO_TIP_STRENGTH],
    tags: ['アコギ', '癒し', 'インスト', 'Udio向け'],
    version: 'v1',
  }),

  // ===== シティポップ =====
  b('bp-citypop', {
    title: '【Suno】ナイトドライブなシティポップ',
    prompt: 'city pop, groovy 110 BPM, funky electric bass and clean guitar, warm electric piano, smooth female vocal, tasteful sax, nostalgic 80s night vibe',
    description: '夜の都会を思わせるシティポップ。Suno向けに要素を絞りつつ80sの空気を出します。',
    genre: 'シティポップ',
    subgenre: 'ファンク寄り',
    emotions: ['ノスタルジック', 'おしゃれ', '穏やか'],
    bpm: 'upper',
    vocal: 'female',
    instruments: ['ベース', 'エレピ', 'サックス'],
    era: '80s',
    uses: ['MV', 'YouTube', '作業用BGM'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「night vibe / electric piano」で世界観が決まる', 'funky bass がグルーヴの土台になる'],
    failurePoints: ['sax を盛ると古臭くなりすぎる', 'グルーヴが甘いと平坦に聞こえる'],
    adjustments: ['古さが気になるなら sax を控え guitar を前へ', SUNO_FAIL_BPM + '(ノリは tight groove の語で補う)'],
    tags: ['シティポップ', '夜', 'おしゃれ', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-citypop-udio', {
    title: '【Udio】ナイトドライブなシティポップ',
    prompt:
      'A groovy, nostalgic 80s city pop track that feels like a night drive through neon-lit streets — funky electric bass, clean chorus guitar, warm electric piano, tasteful sax licks, and a smooth female vocal. Sophisticated, mellow, and stylish, with a lush chorus.',
    description: 'Udio向けにネオンの情景を描いたシティポップ。おしゃれなグルーヴを言葉で作り込めます。',
    genre: 'シティポップ',
    subgenre: 'ファンク寄り',
    emotions: ['ノスタルジック', 'おしゃれ', '穏やか'],
    bpm: 'upper',
    vocal: 'female',
    instruments: ['ベース', 'エレピ', 'サックス'],
    era: '80s',
    uses: ['MV', 'YouTube', '作業用BGM'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「night drive / neon-lit streets」で世界観が濃く出る', 'Udioはグルーヴと質感を両立しやすい'],
    failurePoints: ['sax を盛りすぎると古臭くなる', UDIO_FAIL_CONFLICT],
    adjustments: ['ノリを強めるなら tight groove, syncopation を繰り返す', UDIO_TIP_STRENGTH],
    tags: ['シティポップ', '夜', 'おしゃれ', 'Udio向け'],
    version: 'v1',
  }),

  // ===== R&B =====
  b('bp-rnb-soul', {
    title: '【Suno】しっとりR&B/ソウルバラード',
    prompt: 'smooth R&B soul, slow 72 BPM, warm Rhodes piano and mellow bass, brushed drums, soulful male vocal, gospel-tinged harmonies, intimate and silky',
    description: '大人っぽくしっとりしたR&B。Suno向けに声の表情を主役にした落ち着いた構成です。',
    genre: 'R&B',
    subgenre: 'ソウル',
    emotions: ['大人っぽい', '切ない', '穏やか'],
    bpm: 'slow',
    vocal: 'male',
    instruments: ['エレピ', 'ベース', 'ドラム'],
    era: '2010s',
    uses: ['MV', 'YouTube', 'BGM'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「soulful vocal / gospel harmonies」で表情が豊かに', 'Rhodes+brushed drums で大人の落ち着きが出る'],
    failurePoints: ['コーラスを盛りすぎると主役の声がぼやける', 'テンポが遅く間延びしやすい'],
    adjustments: ['間延びするなら軽いビートを前に出す', '声を立てるなら harmonies を [Chorus: subtle harmonies] に'],
    tags: ['R&B', '大人', 'しっとり', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-rnb-udio', {
    title: '【Udio】官能的なR&Bソウル',
    prompt:
      'A smooth, sensual slow-jam R&B soul ballad — warm Rhodes piano, mellow rounded bass, soft brushed drums, and an intimate soulful male vocal with gospel-tinged backing harmonies. Silky, late-night, and emotional, with a warm, rich mix.',
    description: 'Udio向けに夜の艶を描いたR&B。声とハーモニーの質感を滑らかに再現したいときに。',
    genre: 'R&B',
    subgenre: 'ソウル',
    emotions: ['大人っぽい', '切ない', '穏やか'],
    bpm: 'slow',
    vocal: 'male',
    instruments: ['エレピ', 'ベース', 'ドラム'],
    era: '2010s',
    uses: ['MV', 'YouTube', 'BGM'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「silky / late-night」で艶のある空気が出る', 'Udioは声とハモの質感を滑らかに保てる'],
    failurePoints: ['ハーモニーが厚いと主役の声が沈む', 'テンポが遅く間延びしやすい'],
    adjustments: ['声を立てたいときは backing harmonies を subtle にして繰り返す', UDIO_TIP_STRENGTH],
    tags: ['R&B', '大人', 'しっとり', 'Udio向け'],
    version: 'v1',
  }),

  // ===== ジャンル組み合わせ(フュージョン) =====
  // Suno v5系の書式: ジャンル+時代 → 雰囲気 → 楽器 → ボーカル質感 → プロダクション。
  // 「ボーカルの記述はジャンルタグより効く」ため、声の質感を具体的に書く。
  // 共通タグ 'ジャンルMIX' で組み合わせ系だけを横断検索できる。
  b('bp-fusion-jazzhop', {
    title: '【Suno】Lo-fi × ジャズ(ジャズホップ)',
    prompt: 'jazz-hop, mellow 78 BPM, warm Rhodes and upright bass, brushed drums, chopped sax samples, instrumental, tape-warmed lo-fi mix, contemplative',
    description: 'Lo-fiにジャズの生楽器を混ぜた大人のインスト。作業用でも耳が退屈しない上質さが出ます。',
    genre: 'Lo-fi',
    subgenre: 'ジャズホップ',
    emotions: ['落ち着く', '大人っぽい', 'ノスタルジック'],
    bpm: 'mid',
    vocal: 'instrumental',
    instruments: ['エレピ', 'ウッドベース', 'サックス'],
    era: '2020s',
    uses: ['作業用BGM', 'カフェ', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「upright bass / brushed drums」で生ジャズの質感が出る', 'chopped samples でLo-fiの土臭さが乗る'],
    failurePoints: ['ソロを盛るとBGMから外れる', SUNO_FAIL_BPM],
    adjustments: ['ジャズ寄りなら sax solo、Lo-fi寄りなら vinyl crackle を足す', SUNO_TIP_EXCLUDE],
    tags: ['ジャンルMIX', 'ジャズ', 'チル', '作業用', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-fusion-citypop-ff', {
    title: '【Suno】シティポップ × フューチャーファンク',
    prompt: 'city pop future funk, 1983 nocturnal groove, funky slap bass and Rhodes, gated drums, silky female vocal, filtered disco chops, warm nostalgic mix',
    description: '80sシティポップをダンサブルに再構築したフューチャーファンク。ドライブ映像にも映えます。',
    genre: 'シティポップ',
    subgenre: 'フューチャーファンク',
    emotions: ['おしゃれ', 'ノスタルジック', '高揚'],
    bpm: 'upper',
    vocal: 'female',
    instruments: ['ベース', 'エレピ', 'シンセ'],
    era: '80s',
    uses: ['MV', 'YouTube', 'Shorts'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「filtered disco chops」でフューチャーファンクらしさが出る', 'slap bass がダンス感の核になる'],
    failurePoints: ['チョップを盛りすぎると歌が途切れて聞こえる', SUNO_FAIL_CROWD],
    adjustments: ['踊らせたいなら four-on-the-floor、夜寄りなら mellow を足す', SUNO_TIP_STRUCTURE],
    tags: ['ジャンルMIX', 'シティポップ', 'ダンス', '夜', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-fusion-phonk', {
    title: '【Suno】ドリフトフォンク(フォンク × トラップ)',
    prompt: 'drift phonk, dark 135 BPM, distorted 808 and cowbell melody, fast hi-hats, chopped vocal ad-libs, gritty lo-fi mix, menacing and hypnotic',
    description: 'ShortsやTikTokでバズるダークなフォンク。カウベル旋律と歪んだ808が特徴の疾走系です。',
    genre: 'ヒップホップ',
    subgenre: 'フォンク',
    emotions: ['ダーク', 'かっこいい', '疾走感'],
    bpm: 'fast',
    vocal: 'instrumental',
    instruments: ['808', 'カウベル', 'ハイハット'],
    era: '2020s',
    uses: ['Shorts', 'TikTok', 'ゲーム'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「cowbell melody / distorted 808」でフォンクが即成立する', '歌なしでもフックが強く短尺向き'],
    failurePoints: ['歪みを盛りすぎると耳に痛い', SUNO_FAIL_BPM],
    adjustments: ['メロを強めるなら cowbell melody を前面に', SUNO_TIP_EXCLUDE + '(声を消すなら vocals を除外)'],
    tags: ['ジャンルMIX', 'フォンク', 'ダーク', 'Shorts', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-fusion-hyperpop', {
    title: '【Suno】ハイパーポップ × トラップ',
    prompt: 'hyperpop, euphoric 160 BPM, bright saw synths and 808 bass, pitch-shifted female vocal chops, glitchy maximalist production, punchy viral hook',
    description: 'ピッチを上げた声と過剰なシンセのカオスなハイパーポップ。中毒性のあるフック狙いです。',
    genre: 'エレクトロ',
    subgenre: 'ハイパーポップ',
    emotions: ['高揚', 'かわいい', 'カオス'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['シンセ', '808', 'ボーカルチョップ'],
    era: '2020s',
    uses: ['Shorts', 'TikTok', 'MV'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「pitch-shifted vocal chops」でハイパーポップ感が出る', '「viral hook」で短尺の中毒性が上がる'],
    failurePoints: ['要素過多で音が割れて聞こえる', 'ピッチ上げが強すぎると歌詞が伝わらない'],
    adjustments: ['聴きやすくするなら maximalist を clean に寄せる', SUNO_TIP_STRUCTURE],
    tags: ['ジャンルMIX', 'ハイパーポップ', 'Shorts', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-fusion-synthwave', {
    title: '【Suno】シンセウェイブ × ダークウェイブ',
    prompt: 'synthwave darkwave, 1986 analog arpeggios, layered synthesizers and gated drums, deadpan male vocal, neon-soaked reverb, nostalgic and ominous',
    description: 'ネオン感と不穏さを併せ持つ80sレトロシンセ。ナイトドライブや近未来の映像に合います。',
    genre: 'エレクトロ',
    subgenre: 'シンセウェイブ',
    emotions: ['ノスタルジック', 'ダーク', 'おしゃれ'],
    bpm: 'upper',
    vocal: 'male',
    instruments: ['シンセ', 'ドラムマシン'],
    era: '80s',
    uses: ['MV', 'ゲーム', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「analog arpeggios / neon-soaked reverb」で世界観が即決まる', 'deadpan vocal がレトロ感を強める'],
    failurePoints: ['アルペジオが単調で長尺だと飽きる', SUNO_FAIL_BPM],
    adjustments: ['明るくするなら darkwave を外して dreamy を足す', SUNO_TIP_STRUCTURE],
    tags: ['ジャンルMIX', 'シンセウェイブ', '80s', '夜', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-fusion-trap-orch', {
    title: '【Suno】トラップ × オーケストラ(シネマティック)',
    prompt: 'cinematic trap, intense and grandiose, orchestral strings and brass with hard 808 kicks, fast hi-hats, atmospheric male flow, polished modern orchestration',
    description: 'オーケストラの荘厳さとトラップの重低音を融合。予告編やバトル映像級の迫力が出ます。',
    genre: 'ヒップホップ',
    subgenre: 'シネマティックトラップ',
    emotions: ['壮大', 'かっこいい', '緊張感'],
    bpm: 'mid',
    vocal: 'male',
    instruments: ['ストリングス', 'ブラス', '808'],
    era: '2020s',
    uses: ['MV', '予告編', 'ゲーム'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「orchestral strings with 808」で緊張と重さが両立する', 'atmospheric flow が映像に馴染む'],
    failurePoints: ['オーケストラと808が同じ帯で濁りやすい', SUNO_FAIL_CROWD],
    adjustments: ['歌なしにするなら Instrumental を ON にする', '重さを足すなら low brass を強調'],
    tags: ['ジャンルMIX', 'トラップ', 'シネマティック', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-fusion-afro', {
    title: '【Udio】アフロビーツ × アマピアノ',
    prompt:
      'A groovy, hypnotic Afrobeats and amapiano fusion — deep log-drum bass, warm piano loops, shakers and soft percussion, and smooth call-and-response vocals with ad-libs. Sunny, soulful, and club-ready, with a laid-back but danceable groove.',
    description: 'Udio向けにアフロビーツとアマピアノの陽なグルーヴを描写。世界的に伸びている踊れる系です。',
    genre: 'アフロビーツ',
    subgenre: 'アマピアノ',
    emotions: ['楽しい', 'おしゃれ', '穏やか'],
    bpm: 'upper',
    vocal: 'mixed',
    instruments: ['パーカッション', 'ピアノ', 'ベース'],
    era: '2020s',
    uses: ['MV', 'クラブ', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「log-drum bass / piano loops」でアマピアノ感が出る', 'Udioはグルーヴと空気感を両立しやすい'],
    failurePoints: ['要素を足しすぎるとグルーヴが濁る', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_REPEAT + '(groovy を繰り返す)', UDIO_TIP_STRENGTH],
    tags: ['ジャンルMIX', 'アフロビーツ', 'ダンス', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-fusion-reggaeton', {
    title: '【Udio】レゲトン × ネオソウル',
    prompt:
      'A sensual, late-night blend of reggaeton and neo-soul — a laid-back dembow groove, warm atmospheric pads, mellow electric piano, and breathy intimate vocals. Smooth, romantic, and modern, with a reverb-heavy, spacious mix.',
    description: 'Udio向けにレゲトンのリズムとネオソウルの艶を融合。夜の大人っぽいラテン系です。',
    genre: 'ラテン',
    subgenre: 'レゲトン',
    emotions: ['大人っぽい', 'おしゃれ', '穏やか'],
    bpm: 'mid',
    vocal: 'mixed',
    instruments: ['パーカッション', 'エレピ', 'パッド'],
    era: '2020s',
    uses: ['MV', 'YouTube', 'BGM'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「dembow groove」でラテンのノリが出る', 'breathy vocals が艶を足す'],
    failurePoints: ['dembow を強めすぎると落ち着きが消える', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_STRENGTH, '明るくするなら tropical、夜寄りなら moody を足す'],
    tags: ['ジャンルMIX', 'ラテン', '夜', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-fusion-folktronica', {
    title: '【Udio】フォークトロニカ(フォーク × エレクトロニカ)',
    prompt:
      'An atmospheric folktronica track where acoustic folk meets gentle electronica — fingerpicked acoustic guitar, subtle synth pads, soft clicky electronic percussion, and warm conversational vocals. Literary, intimate, and dreamy, with an indie production feel.',
    description: 'Udio向けにアコースティックとエレクトロニカの中間を描写。内省的で映像的なインディー系です。',
    genre: 'フォーク',
    subgenre: 'フォークトロニカ',
    emotions: ['内省的', '穏やか', 'ノスタルジック'],
    bpm: 'mid',
    vocal: 'mixed',
    instruments: ['アコースティックギター', 'シンセ', 'パーカッション'],
    era: '2010s',
    uses: ['MV', 'Vlog', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「acoustic folk meets electronica」で中間の質感が出る', 'conversational vocals が親密さを足す'],
    failurePoints: ['エレクトロを強めると素朴さが消える', 'Prompt Strength が低いと生楽器が薄まる'],
    adjustments: [UDIO_TIP_STRENGTH, '電子寄りにするなら glitch percussion を足す'],
    tags: ['ジャンルMIX', 'フォーク', 'インディー', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-fusion-dnb-jazz', {
    title: '【Suno】ドラムンベース × ジャズ(リキッド)',
    prompt: 'liquid drum and bass, 174 BPM, chopped breakbeats and deep sub bass, live saxophone and Rhodes, smooth female vocal, atmospheric virtuosic mix',
    description: '疾走するブレイクビーツにジャズの生楽器を乗せたリキッドDnB。爽快かつ上質です。',
    genre: 'エレクトロ',
    subgenre: 'ドラムンベース',
    emotions: ['爽快', 'おしゃれ', '疾走感'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['ブレイクビーツ', 'サックス', 'エレピ'],
    era: '2020s',
    uses: ['MV', 'クラブ', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「chopped breakbeats / deep sub bass」でDnBの土台が決まる', 'live sax が上質さを足す'],
    failurePoints: ['テンポが速く歌が詰め込み気味になる', SUNO_FAIL_BPM],
    adjustments: ['歌を減らすなら instrumental に寄せる', SUNO_TIP_STRUCTURE],
    tags: ['ジャンルMIX', 'ドラムンベース', 'ジャズ', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-fusion-kpop', {
    title: '【Suno】K-POP × EDM × ヒップホップ',
    prompt: 'K-pop, upbeat 125 BPM, punchy synths and 808, rap verse and powerful female chorus, glossy maximalist production, catchy hook, energetic and polished',
    description: 'ラップ・歌・EDMドロップを詰めたグローバルK-POP型。展開の起伏で飽きさせない構成です。',
    genre: 'K-POP',
    subgenre: 'ダンスポップ',
    emotions: ['高揚', 'かっこいい', 'キャッチー'],
    bpm: 'fast',
    vocal: 'mixed',
    instruments: ['シンセ', '808', 'ドラム'],
    era: '2020s',
    uses: ['MV', 'Shorts', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「rap verse and powerful chorus」で起伏が作れる', 'glossy production でK-POPらしい艶が出る'],
    failurePoints: ['詰め込みすぎて散らかりやすい', SUNO_FAIL_CROWD],
    adjustments: ['構成は [Verse: rap] → [Chorus: sung] と : で指定', 'ドロップを足すなら [Dance Break] を置く'],
    tags: ['ジャンルMIX', 'K-POP', 'ダンス', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-fusion-neosoul', {
    title: '【Udio】ネオソウル × ヒップホップ',
    prompt:
      'A warm, jazzy neo-soul track with a hip-hop backbone — laid-back boom-bap drums, deep round bass, lush Rhodes chords, subtle horns, and a smooth soulful vocal with rich harmonies. Mellow, romantic, and organic, with a warm analog mix.',
    description: 'Udio向けにネオソウルの温かさとヒップホップのビートを融合。落ち着いた大人の一曲に。',
    genre: 'ネオソウル',
    subgenre: 'ヒップホップソウル',
    emotions: ['大人っぽい', '穏やか', 'おしゃれ'],
    bpm: 'mid',
    vocal: 'male',
    instruments: ['エレピ', 'ベース', 'ドラム'],
    era: '2010s',
    uses: ['MV', 'YouTube', 'BGM'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「lush Rhodes chords / rich harmonies」で厚みと温かさが出る', 'Udioは声とハモの質感が滑らか'],
    failurePoints: ['ハモを盛りすぎると主役の声が沈む', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_STRENGTH, 'ジャズ寄りにするなら horns を強調'],
    tags: ['ジャンルMIX', 'ネオソウル', '大人', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-fusion-symphonic-metal', {
    title: '【Suno】シンフォニックメタル(メタル × オーケストラ)',
    prompt: 'symphonic metal, epic 145 BPM, distorted guitars and double-kick drums, sweeping orchestra and choir, powerful soprano female vocal, cinematic and bombastic',
    description: 'メタルの重さにオーケストラと合唱を重ねた荘厳な一曲。ラスボスや壮大な映像に向きます。',
    genre: 'メタル',
    subgenre: 'シンフォニックメタル',
    emotions: ['壮大', '力強い', '緊張感'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['エレキギター', 'ドラム', 'オーケストラ'],
    era: '2010s',
    uses: ['MV', 'ゲーム', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「sweeping orchestra and choir」で荘厳さが出る', 'soprano vocal がドラマ性を足す'],
    failurePoints: ['ギターとオーケストラが同じ帯で団子になりやすい', SUNO_FAIL_CROWD],
    adjustments: ['サビを強めるなら [Chorus: full choir, soaring vocals]', SUNO_TIP_EXCLUDE],
    tags: ['ジャンルMIX', 'メタル', 'オーケストラ', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-fusion-country-pop', {
    title: '【Suno】カントリー × ポップ',
    prompt: 'modern country pop, warm mid-tempo 100 BPM, acoustic guitar and banjo with punchy drums, bright female vocal, clap groove, wholesome and catchy',
    description: 'アコースティックの温かさにポップのフックを効かせたモダンカントリー。前向きで親しみやすい。',
    genre: 'カントリー',
    subgenre: 'カントリーポップ',
    emotions: ['前向き', '温かい', 'キャッチー'],
    bpm: 'mid',
    vocal: 'female',
    instruments: ['アコースティックギター', 'バンジョー', 'ドラム'],
    era: '2020s',
    uses: ['MV', 'YouTube', 'Vlog'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「banjo / clap groove」でカントリー感が出る', '明るいポップのフックで親しみやすい'],
    failurePoints: ['バンジョーを盛ると古風になりすぎる', SUNO_FAIL_BPM],
    adjustments: ['都会的にするなら banjo を外して synth を足す', SUNO_TIP_STRUCTURE],
    tags: ['ジャンルMIX', 'カントリー', '明るい', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-fusion-tropical-house', {
    title: '【Udio】トロピカルハウス × ポップ',
    prompt:
      'A breezy, summery tropical house pop song — plucky marimba and steel-pan leads, warm sidechained chords, a light four-on-the-floor groove, and a bright airy female vocal. Uplifting, sunny, and relaxed, with a polished radio-friendly mix.',
    description: 'Udio向けに夏の爽やかさを描写したトロピカルハウス。明るく開放的なポップドロップが特徴です。',
    genre: 'EDM',
    subgenre: 'トロピカルハウス',
    emotions: ['爽やか', '前向き', '穏やか'],
    bpm: 'upper',
    vocal: 'female',
    instruments: ['シンセ', 'マリンバ', 'キック'],
    era: '2010s',
    uses: ['MV', 'YouTube', 'Vlog'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「marimba / steel-pan」でトロピカル感が即出る', '「summery / sunny」で開放感が乗る'],
    failurePoints: ['要素を足すと爽やかさが濁る', 'Prompt Strength が低いと平凡なハウスになる'],
    adjustments: [UDIO_TIP_REPEAT + '(summery を繰り返す)', UDIO_TIP_STRENGTH],
    tags: ['ジャンルMIX', 'トロピカルハウス', '夏', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-fusion-neoclassical', {
    title: '【Udio】ネオクラシカル(ピアノ × シネマティック)',
    prompt:
      'A tender neo-classical piece — expressive solo piano at the center, gentle swelling strings, subtle ambient pads, and delicate texture. Emotional, cinematic, and intimate, building slowly to a moving climax. Instrumental, no drums, no vocals.',
    description: 'Udio向けにピアノ主体の現代クラシックを描写。感動的な映像やエンディングBGMに向きます。',
    genre: 'インストゥルメンタル',
    subgenre: 'ネオクラシカル',
    emotions: ['感動的', '切ない', '静か'],
    bpm: 'slow',
    vocal: 'instrumental',
    instruments: ['ピアノ', 'ストリングス', 'パッド'],
    era: '2020s',
    uses: ['BGM', 'MV', '映像'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「solo piano / swelling strings」で感動的な展開が作れる', 'Udioは生ピアノの表情を滑らかに再現する'],
    failurePoints: ['盛り込みすぎると静けさが失われる', 'Prompt Strength が低いとリズムが混ざる'],
    adjustments: ['「no drums / no vocals」を明記する', UDIO_TIP_STRENGTH],
    tags: ['ジャンルMIX', 'ネオクラシカル', 'ピアノ', 'インスト', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-fusion-jazz-bossa', {
    title: '【Suno】ジャズ × ボサノヴァ(ラウンジ)',
    prompt: 'bossa nova jazz, relaxed 120 BPM, nylon guitar and brushed drums, upright bass and gentle piano, soft warm female vocal, mellow lounge mix, sophisticated',
    description: 'ボサノヴァの心地よさにジャズの洗練を効かせたラウンジ系。カフェや上品な場面に合います。',
    genre: 'ジャズ',
    subgenre: 'ボサノヴァ',
    emotions: ['おしゃれ', '穏やか', '大人っぽい'],
    bpm: 'upper',
    vocal: 'female',
    instruments: ['ナイロンギター', 'ウッドベース', 'ピアノ'],
    era: 'timeless',
    uses: ['カフェ', 'BGM', '作業用BGM'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「nylon guitar / brushed drums」でボサの質感が出る', 'soft warm vocal が上品さを足す'],
    failurePoints: ['楽器を増やすとラウンジの軽さが消える', SUNO_FAIL_BPM],
    adjustments: ['インストにするなら vocal を外して piano solo を足す', SUNO_TIP_EXCLUDE],
    tags: ['ジャンルMIX', 'ジャズ', 'ボサノヴァ', 'カフェ', 'Suno向け'],
    version: 'v1',
  }),

  // ===== 最新トレンド(Suno等で今よく作られている人気スタイル) =====
  // 実在アーティスト名は両ツールで効かず/フィルタされるため、人気の鳴りは
  // ジャンル×時代×楽器×ボーカル質感×プロダクションへ翻訳して記述する。共通タグ 'トレンド'。
  b('bp-trend-corridos', {
    title: '【Suno】コリドス・トゥンバドス(レジオナル・メヒカーノ)',
    prompt: 'corridos tumbados, regional Mexican, requinto and 12-string acoustic guitar, tuba bass, mid-tempo, warm male vocal, narrative storytelling, trap-influenced, acoustic warm mix',
    description: '世界チャート常連のメキシコ系。生ギターとチューバにトラップの間を混ぜたモダンな語り物です。',
    genre: 'ラテン',
    subgenre: 'コリド',
    emotions: ['エモい', '大人っぽい', 'ノスタルジック'],
    bpm: 'mid',
    vocal: 'male',
    instruments: ['アコースティックギター', 'チューバ', 'レキント'],
    era: '2020s',
    uses: ['MV', 'YouTube', 'Shorts'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「requinto / tuba bass」でレジオナル感が即出る', 'trap-influenced で今っぽさが乗る'],
    failurePoints: ['楽器を増やすと生の生々しさが薄れる', SUNO_FAIL_BPM],
    adjustments: ['歌詞はスペイン語にすると本場の質感になる', SUNO_TIP_STRUCTURE],
    tags: ['トレンド', 'ラテン', 'アコースティック', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-trend-drill', {
    title: '【Suno】ドリル(UK/NYドリル)',
    prompt: 'UK drill, dark 142 BPM, sliding 808 bass and skippy hi-hats, ominous piano and string stabs, gritty male rap flow, moody and cinematic mix',
    description: 'スライド808と跳ねるハットが特徴のダークなドリル。緊張感のあるストリート系トラックです。',
    genre: 'ヒップホップ',
    subgenre: 'ドリル',
    emotions: ['ダーク', 'かっこいい', '緊張感'],
    bpm: 'fast',
    vocal: 'male',
    instruments: ['808', 'ハイハット', 'ストリングス'],
    era: '2020s',
    uses: ['MV', 'Shorts', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「sliding 808 / skippy hi-hats」でドリルの土台が決まる', 'string stabs で不穏さが増す'],
    failurePoints: ['ラップの譜割りが詰まりやすい', SUNO_FAIL_BPM],
    adjustments: ['歌なしにするなら Instrumental を ON にする', SUNO_TIP_EXCLUDE],
    tags: ['トレンド', 'ドリル', 'ダーク', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-trend-boombap', {
    title: '【Suno】ブーンバップ(90sヒップホップ)',
    prompt: 'boom-bap hip hop, 90s, 90 BPM, dusty sampled drums and vinyl scratches, jazzy piano loop, warm upright bass, laid-back male rap, gritty analog mix',
    description: '埃っぽいドラムとジャジーなループの90s直系ヒップホップ。硬派で温かいトラックです。',
    genre: 'ヒップホップ',
    subgenre: 'ブーンバップ',
    emotions: ['ノスタルジック', 'かっこいい', '大人っぽい'],
    bpm: 'mid',
    vocal: 'male',
    instruments: ['ドラム', 'ピアノ', 'ウッドベース'],
    era: '90s',
    uses: ['MV', 'YouTube', 'BGM'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「dusty drums / vinyl scratches」で90s感が即出る', 'jazzy loop が硬派さと温かさを両立'],
    failurePoints: ['ループが単調で長尺だと飽きる', SUNO_FAIL_BPM],
    adjustments: ['インストにするなら vocal を外して scratches を足す', SUNO_TIP_STRUCTURE],
    tags: ['トレンド', 'ブーンバップ', 'レトロ', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-trend-gospel', {
    title: '【Suno】ゴスペル/ワーシップ',
    prompt: 'uplifting gospel, warm mid-tempo, Hammond organ and grand piano, powerful lead vocal with full choir, hand claps, soulful and euphoric, rich live mix',
    description: '合唱とオルガンで高揚する感動的なゴスペル。前向きで魂を揺さぶる盛り上がりが作れます。',
    genre: 'ゴスペル',
    subgenre: 'ワーシップ',
    emotions: ['感動的', '前向き', '高揚'],
    bpm: 'mid',
    vocal: 'mixed',
    instruments: ['オルガン', 'ピアノ', 'コーラス'],
    era: 'timeless',
    uses: ['MV', 'YouTube', '合唱'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「full choir / Hammond organ」で高揚感が確実に出る', 'hand claps がライブの一体感を足す'],
    failurePoints: ['合唱を盛りすぎると主役の声が埋もれる', SUNO_FAIL_CROWD],
    adjustments: ['ラスサビを強めるなら [Chorus: full choir, soaring lead]', SUNO_TIP_STRUCTURE],
    tags: ['トレンド', 'ゴスペル', '感動', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-trend-indie-rock', {
    title: '【Suno】インディーロック(ジャングリー)',
    prompt: 'indie rock, jangly bright guitars, mid-tempo 118 BPM, melodic bass and crisp drums, earnest male vocal, catchy hooks, warm lo-fi indie production',
    description: 'きらっとしたギターと素朴な歌のインディーロック。青春感のあるエモーショナルな一曲に。',
    genre: 'インディー',
    subgenre: 'インディーロック',
    emotions: ['エモい', '前向き', 'ノスタルジック'],
    bpm: 'upper',
    vocal: 'male',
    instruments: ['エレキギター', 'ベース', 'ドラム'],
    era: '2010s',
    uses: ['MV', 'YouTube', 'Vlog'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「jangly bright guitars」でインディーの空気が出る', 'earnest vocal が青春感を足す'],
    failurePoints: ['プロダクションを磨きすぎると素朴さが消える', SUNO_FAIL_BPM],
    adjustments: ['ドリーミーにするなら reverb-drenched を足す', SUNO_TIP_STRUCTURE],
    tags: ['トレンド', 'インディー', 'ギター', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-trend-dreampop', {
    title: '【Udio】ドリームポップ/シューゲイズ',
    prompt:
      'A hazy, ethereal dream pop / shoegaze track — walls of reverb-drenched shimmering guitars, soft washy synths, gentle steady drums, and breathy dreamy female vocals buried in the mix. Nostalgic, blissful, and atmospheric, with a lush wide sound.',
    description: 'Udio向けにリバーブの海に沈む浮遊感を描写。ノスタルジックで幻想的なインディー系です。',
    genre: 'インディー',
    subgenre: 'ドリームポップ',
    emotions: ['ノスタルジック', '透明感', '穏やか'],
    bpm: 'mid',
    vocal: 'female',
    instruments: ['エレキギター', 'シンセ', 'ドラム'],
    era: '2010s',
    uses: ['MV', 'YouTube', 'BGM'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「reverb-drenched / buried in the mix」で浮遊感が出る', 'Udioは広い残響を滑らかに保てる'],
    failurePoints: ['声を埋めすぎると歌詞が届かない', UDIO_FAIL_CONFLICT],
    adjustments: ['声を前に出すなら buried in the mix を外す', UDIO_TIP_STRENGTH],
    tags: ['トレンド', 'ドリームポップ', '浮遊感', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-trend-melodic-techno', {
    title: '【Suno】メロディックテクノ',
    prompt: 'melodic techno, hypnotic 122 BPM, driving four-on-the-floor kick, arpeggiated synths, deep rolling bass, atmospheric pads, instrumental, dark and euphoric',
    description: '反復と徐々の展開で没入させるメロディックテクノ。クラブや長尺の映像BGMに向きます。',
    genre: 'EDM',
    subgenre: 'メロディックテクノ',
    emotions: ['没入感', 'ダーク', '高揚'],
    bpm: 'upper',
    vocal: 'instrumental',
    instruments: ['シンセ', 'キック', 'ベース'],
    era: '2020s',
    uses: ['クラブ', 'BGM', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「hypnotic / arpeggiated synths」で没入感が出る', '徐々の展開で長尺が持つ'],
    failurePoints: ['展開を付けすぎると催眠感が壊れる', SUNO_FAIL_BPM],
    adjustments: ['明るくするなら dark を uplifting に置き換える', SUNO_TIP_EXCLUDE],
    tags: ['トレンド', 'テクノ', 'クラブ', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-trend-nudisco', {
    title: '【Suno】ヌーディスコ/ディスコハウス',
    prompt: 'nu-disco, groovy 115 BPM, funky filtered guitar and disco strings, four-on-the-floor drums, slap bass, soulful female vocal, glossy retro-modern mix',
    description: 'ディスコの高揚を現代的に磨いたヌーディスコ。踊れておしゃれ、明るいMVにも合います。',
    genre: 'EDM',
    subgenre: 'ヌーディスコ',
    emotions: ['高揚', 'おしゃれ', '楽しい'],
    bpm: 'upper',
    vocal: 'female',
    instruments: ['ギター', 'ストリングス', 'ベース'],
    era: '2020s',
    uses: ['MV', 'クラブ', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「filtered guitar / disco strings」でディスコ感が出る', 'slap bass が踊れるノリを作る'],
    failurePoints: ['ストリングスを盛ると古臭くなる', SUNO_FAIL_BPM],
    adjustments: ['現代寄りにするなら synth を強め、レトロ寄りなら strings を強める', SUNO_TIP_STRUCTURE],
    tags: ['トレンド', 'ディスコ', 'ダンス', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-trend-cinematic-trailer', {
    title: '【Udio】シネマティック予告編(エピック)',
    prompt:
      'An epic cinematic trailer cue that builds from a quiet, tense intro to a massive climax — deep booming hits, staccato strings, huge brass, pounding percussion, and a soaring choir. Dramatic, heroic, and overwhelming, instrumental with no vocals.',
    description: 'Udio向けに「静→爆発」の予告編構成を描写。映像の山場やゲームトレーラーに使える壮大なインスト。',
    genre: 'シネマティック',
    subgenre: 'トレーラー',
    emotions: ['壮大', '緊張感', '高揚'],
    bpm: 'mid',
    vocal: 'instrumental',
    instruments: ['ストリングス', 'ブラス', 'パーカッション'],
    era: 'timeless',
    uses: ['予告編', '映像', 'ゲーム'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「builds to a massive climax」で予告編の山が作れる', 'booming hits が迫力を足す'],
    failurePoints: ['要素過多で山場が団子になる', 'Prompt Strength が低いと盛り上がりが弱い'],
    adjustments: ['「no vocals」を明記して繰り返す', UDIO_TIP_STRENGTH],
    tags: ['トレンド', 'シネマティック', 'オーケストラ', 'インスト', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-trend-singer-songwriter', {
    title: '【Udio】アコースティック弾き語り(シンガーソングライター)',
    prompt:
      'An intimate acoustic singer-songwriter ballad — a single fingerpicked acoustic guitar, subtle warm room ambience, and a tender, emotive vocal delivered close to the mic. Honest, vulnerable, and heartfelt, with a raw, stripped-back production.',
    description: 'Udio向けに一本のギターと歌だけの弾き語りを描写。飾らない生々しさで言葉が刺さります。',
    genre: 'フォーク',
    subgenre: 'シンガーソングライター',
    emotions: ['切ない', '温かい', '内省的'],
    bpm: 'slow',
    vocal: 'mixed',
    instruments: ['アコースティックギター'],
    era: 'timeless',
    uses: ['MV', 'YouTube', 'Vlog'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「close to the mic / stripped-back」で生々しさが出る', 'Udioは声の息づかいを繊細に再現'],
    failurePoints: ['伴奏を足すと弾き語りの親密さが薄れる', 'Prompt Strength が低いと編成が増える'],
    adjustments: ['サビだけ厚くしたいなら中盤から strings を足す', UDIO_TIP_STRENGTH],
    tags: ['トレンド', '弾き語り', 'アコースティック', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-trend-poppunk', {
    title: '【Suno】ポップパンク(2000s)',
    prompt: 'pop punk, fast 170 BPM, bright distorted power chords, punchy fast drums, melodic bass, energetic youthful male vocal, catchy gang-vocal chorus, polished but raw',
    description: '2000s直系の疾走ポップパンク。青春の勢いとキャッチーな合唱サビが気持ちいい一曲です。',
    genre: 'ロック',
    subgenre: 'ポップパンク',
    emotions: ['熱い', '前向き', '疾走感'],
    bpm: 'fast',
    vocal: 'male',
    instruments: ['エレキギター', 'ベース', 'ドラム'],
    era: '2000s',
    uses: ['MV', 'ライブ', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「gang-vocal chorus」で合唱サビが盛り上がる', 'power chords で疾走感が出る'],
    failurePoints: ['歪みを盛ると歌が埋もれる', SUNO_FAIL_BPM],
    adjustments: ['サビを厚くするなら [Chorus: gang vocals]', SUNO_TIP_STRUCTURE],
    tags: ['トレンド', 'ポップパンク', 'バンド', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-trend-altrnb', {
    title: '【Suno】オルタナR&B/トラップソウル',
    prompt: 'alternative R&B, dark and atmospheric, slow 70 BPM, sparse trap drums and deep 808, moody synth pads, breathy layered male vocal, spacious moody mix',
    description: '余白と低音で聴かせるダークなオルタナR&B。夜の都会的で内省的なムードが作れます。',
    genre: 'R&B',
    subgenre: 'オルタナR&B',
    emotions: ['ダーク', '大人っぽい', '切ない'],
    bpm: 'slow',
    vocal: 'male',
    instruments: ['808', 'シンセ', 'ドラム'],
    era: '2020s',
    uses: ['MV', 'YouTube', 'BGM'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「sparse drums / deep 808」で余白と低音が効く', 'breathy layered vocal が現代的な質感を出す'],
    failurePoints: ['音を詰めると余白の緊張感が消える', SUNO_FAIL_BPM],
    adjustments: ['明るくするなら dark を warm に置き換える', SUNO_TIP_EXCLUDE],
    tags: ['トレンド', 'オルタナR&B', '夜', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-trend-wafu', {
    title: '【Suno】和風(琴・尺八 × シネマティック)',
    prompt: 'Japanese traditional cinematic, koto and shakuhachi flute, taiko drums, sweeping strings, instrumental, epic and serene, blend of traditional and modern, atmospheric mix',
    description: '琴・尺八・太鼓に現代オーケストラを重ねた和風シネマティック。和のゲーム・アニメ映像に。',
    genre: '和風',
    subgenre: '和風シネマティック',
    emotions: ['壮大', '静か', '緊張感'],
    bpm: 'mid',
    vocal: 'instrumental',
    instruments: ['琴', '尺八', '太鼓'],
    era: 'timeless',
    uses: ['ゲーム', '映像', 'BGM'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「koto / shakuhachi / taiko」で和の情景が即出る', 'strings 追加で映像的な厚みが出る'],
    failurePoints: ['洋楽器を盛りすぎると和が薄れる', SUNO_FAIL_CROWD],
    adjustments: ['静けさ重視なら太鼓を抜き、迫力重視なら太鼓を強める', SUNO_TIP_EXCLUDE],
    tags: ['トレンド', '和風', 'オーケストラ', 'インスト', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-trend-reggae', {
    title: '【Udio】レゲエ/ダブ',
    prompt:
      'A laid-back, sunny roots reggae track with a dub feel — a deep rolling bass line, off-beat skanking guitar, warm organ bubble, one-drop drums, and a relaxed soulful vocal. Mellow, positive, and spacious, with tape echo and a warm analog mix.',
    description: 'Udio向けにゆったりしたレゲエのグルーヴを描写。陽で心地よく、夏やVlogのBGMに合います。',
    genre: 'レゲエ',
    subgenre: 'ルーツレゲエ',
    emotions: ['穏やか', '前向き', '温かい'],
    bpm: 'mid',
    vocal: 'mixed',
    instruments: ['ベース', 'ギター', 'オルガン'],
    era: 'timeless',
    uses: ['BGM', 'Vlog', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「off-beat skank / one-drop drums」でレゲエのノリが出る', 'tape echo がダブの空気を足す'],
    failurePoints: ['要素を足すとゆるさが消える', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_STRENGTH, 'ダブ寄りにするなら echo / reverb を繰り返し強調'],
    tags: ['トレンド', 'レゲエ', '夏', 'Udio向け'],
    version: 'v1',
  }),
]
